apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: history
      app.kubernetes.io/component: history
      app.kubernetes.io/instance: history
    name: nodejs-12
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/ubi8/nodejs-12
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/nodejs-12
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: history
      app.kubernetes.io/component: history
      app.kubernetes.io/instance: history
    name: history
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: history
      app.kubernetes.io/component: history
      app.kubernetes.io/instance: history
    name: history
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: history:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: history
      git:
        uri: https://github.com/ricardoalonso/exchange-application.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs-12:latest
      type: Docker
    triggers:
    - github:
        secret: gOijGDf7OQ5-WgHGgKvJ
      type: GitHub
    - generic:
        secret: Tkk-JPMUUbq9IZu5lPQU
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"history:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"history\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: history
      app.kubernetes.io/component: history
      app.kubernetes.io/instance: history
    name: history
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: history
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: history
      spec:
        containers:
        - image: ' '
          name: history
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: history
      app.kubernetes.io/component: history
      app.kubernetes.io/instance: history
    name: history
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: history
  status:
    loadBalancer: {}
kind: List
metadata: {}
